import type { Metadata } from 'next';
import Script from 'next/script';
import { Suspense } from 'react';
import { ThemeProvider } from '@/components/theme-provider';
import RouteLoadingBar from '@/components/route-loading-bar';
import './globals.css';

const SITE_URL = 'https://quantumcv.app';

// Homepage title + description (59 / 153 characters, inside Google's display limits).
const TITLE = 'ATS-Ready Resume Builder for Freshers — Free AI | QuantumCV';
const DESCRIPTION =
  'Build an ATS-ready resume as a fresher or student. Free AI resume builder with an instant ATS score, 30 templates and chat editing. No experience needed.';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    // Used on the homepage and any page that doesn't set its own title.
    default: TITLE,
    // Other pages: "Pricing — QuantumCV", "Resume Analyser — QuantumCV", etc.
    template: '%s — QuantumCV',
  },
  description: DESCRIPTION,
  applicationName: 'QuantumCV',
  keywords: [
    'ATS ready resume builder',
    'ATS friendly resume builder',
    'resume builder for freshers',
    'free AI resume builder',
    'free ATS resume score checker',
    'resume builder for students',
    'fresher resume',
  ],
  authors: [{ name: 'QuantumCV', url: SITE_URL }],
  creator: 'QuantumCV',
  publisher: 'QuantumCV',
  category: 'Career',
  // NOTE: do not add `alternates.canonical` here. A canonical set in the root
  // layout is inherited by every page and would point them all at one URL.
  // Set it per page instead (the homepage does it in app/page.tsx).
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  openGraph: {
    type: 'website',
    url: SITE_URL,
    siteName: 'QuantumCV',
    title: TITLE,
    description: DESCRIPTION,
    // og-image is auto-generated by src/app/opengraph-image.tsx (Next.js
    // file convention) — no need to list it here explicitly.
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    // handle updated once the X account is live
    site: '@quantumcv',
  },
  icons: {
    icon: '/icon',
    apple: '/apple-icon',
  },
  // After you add the site in Google Search Console and choose the
  // "HTML tag" method, paste ONLY the content value here and uncomment:
  // verification: { google: 'PASTE_YOUR_CODE_HERE' },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Load gtag.js */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-GN7CM2GRR2"
          strategy="afterInteractive"
        />
        {/* Initialize gtag */}
        <Script id="gtag-init" strategy="afterInteractive">
          {`window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-GN7CM2GRR2');`}
        </Script>
      </head>
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Suspense fallback={null}>
            <RouteLoadingBar />
          </Suspense>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
