import type { Metadata } from 'next';
import { Suspense } from 'react';
import { ThemeProvider } from '@/components/theme-provider';
import RouteLoadingBar from '@/components/route-loading-bar';
import './globals.css';

const SITE_URL = 'https://quantumcv.app';
const TITLE = 'QuantumCV — AI Resume Builder';
const DESCRIPTION =
  'Build resumes that get you hired. AI-powered resume generation, live chat-based editing, and 30 ATS-optimised templates.';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: '%s — QuantumCV',
  },
  description: DESCRIPTION,
  applicationName: 'QuantumCV',
  openGraph: {
    type: 'website',
    url: SITE_URL,
    siteName: 'QuantumCV',
    title: TITLE,
    description: DESCRIPTION,
    // og-image is auto-generated by src/app/opengraph-image.tsx (Next.js
    // file convention) — no need to list it here explicitly, but locale
    // helps some platforms render correctly.
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    // handle updated once the X account is live
    site: '@quantumcv',
  },
  icons: {
    icon: '/icon',
    apple: '/apple-icon',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Suspense fallback={null}>
            <RouteLoadingBar />
          </Suspense>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
