import Link from 'next/link';
import LegalPage from '@/components/legal-page';

export const metadata = {
  title: 'Terms of Service — QuantumCV',
  description: 'The terms that govern using QuantumCV to build, edit, and export resumes.',
};

export default function TermsPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Terms of Service"
      description="These terms cover your use of QuantumCV — please read them before generating or exporting a resume."
      sections={[
        {
          title: 'Acceptance of terms',
          content: (
            <p>
              By creating an account or using QuantumCV in any way, you agree to these Terms of Service and to our{' '}
              <Link href="/privacy">Privacy Policy</Link>. If you don&apos;t agree, please don&apos;t use the service.
            </p>
          ),
        },
        {
          title: 'What QuantumCV does',
          content: (
            <p>
              QuantumCV is a resume-building tool. You provide career information — education, experience, projects,
              skills — and our AI structures it into a formatted resume using one of our templates. You can edit the
              result, chat with the AI to request changes, and export a PDF.
            </p>
          ),
        },
        {
          title: 'Your account',
          content: (
            <ul>
              <li>You&apos;re responsible for the accuracy of the career data you submit and for keeping your login credentials secure.</li>
              <li>You must be at least 16 years old to create an account.</li>
              <li>One account per person — don&apos;t share credentials or resell access.</li>
            </ul>
          ),
        },
        {
          title: 'AI-generated content',
          content: (
            <p>
              Resume content is generated by an AI model based on what you submit. We work to keep output accurate
              and relevant, but you&apos;re responsible for reviewing everything before sending a resume to an
              employer — never submit AI-written content you haven&apos;t verified as true and accurate about
              yourself.
            </p>
          ),
        },
        {
          title: 'Credits, payments & refunds',
          content: (
            <ul>
              <li>Credits are purchased as one-time packs and don&apos;t expire.</li>
              <li>Generating a resume, chat-editing, and the bullet enhancer each consume credits as shown on the <Link href="/pricing">pricing page</Link>.</li>
              <li>Payments are processed securely through Razorpay; we don&apos;t store your card details.</li>
              <li>Because credits are consumed on use, purchases are non-refundable once a credit has been spent. Unused credit packs can be refunded within 7 days of purchase — contact us to request one.</li>
            </ul>
          ),
        },
        {
          title: 'Acceptable use',
          content: (
            <p>
              Don&apos;t use QuantumCV to generate fraudulent, defamatory, or misleading content about yourself or
              anyone else, attempt to reverse-engineer or scrape the service, or interfere with its normal operation.
              We may suspend accounts that violate this.
            </p>
          ),
        },
        {
          title: 'Termination',
          content: (
            <p>
              You can delete your account at any time from your dashboard settings. We may suspend or terminate
              accounts that violate these terms, with notice where practical.
            </p>
          ),
        },
        {
          title: 'Limitation of liability',
          content: (
            <p>
              QuantumCV is provided &ldquo;as is.&rdquo; We don&apos;t guarantee that a generated resume will result
              in interviews or job offers, and we&apos;re not liable for hiring outcomes, indirect damages, or
              content you submit to third parties.
            </p>
          ),
        },
        {
          title: 'Changes to these terms',
          content: (
            <p>
              We may update these terms as the product evolves. Material changes will be announced in-app or by
              email before they take effect.
            </p>
          ),
        },
        {
          title: 'Contact',
          content: (
            <p>
              Questions about these terms? Reach us at{' '}
              <a href="mailto:support@quantumcv.app">support@quantumcv.app</a> or through the{' '}
              <Link href="/contact">contact page</Link>.
            </p>
          ),
        },
      ]}
    />
  );
}